title: Nino 的自留地
description: 记住平凡
lang: zh-CN
timezone: Asia/Shanghai
url: "https://nino-bo.github.io"
baseurl: ""
permalink: /essays/:title/
defaults:
  - scope:
      path: ""
    values:
      layout: default
